server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 向 eureka 中注册
    register-with-eureka: true
    # 在注册中心获取注册信息
    fetch-registry: true
    service-url:
      # 设置 eureka-server 的地址
      defaultZone: http://localhost:7001/eureka/