server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      # 在此处配置要绑定的 rabbitmq 的服务信息
      binders:
        # 表示定义的名称，用于 binding 整合
        defaultRabbit:
          # 消息组件类型
          type: rabbit
          # 设置 rabbitmq 相关的环境配置
          environment:
            spring:
              rabbitmq:
                host: 192.168.23.21
                port: 5672
                username: guest
                password: guest
      # 服务的整合处理
      bindings:
        # 定义通道的名称
        output:
          # 表示要使用的 Exchange 名称
          destination: studyExchange
          # 设置消息类型，本次为 json，文本则设置“text/plain”
          content-type: application/json
          # 设置要绑定的消息服务的具体设置
          binder: defaultRabbit

eureka:
  client:
    # 向 eureka 中注册
    register-with-eureka: true
    # 在注册中心获取注册信息
    fetch-registry: true
    service-url:
      # 设置 eureka-server 的地址
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
