server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # 开启在服务中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        # 路由 id ，没有固定要求，但是必须唯一
        - id: payment-route
          # 匹配后提供服务的路由地址
          #uri: http://localhost:8031
          uri: lb://cloud-hystrix-payment-service
          # 断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/success

        - id: payment-route2
#          uri: http://localhost:8031
          uri: lb://cloud-hystrix-payment-service
          predicates:
            - Path=/payment/timeout

eureka:
  client:
    # 向 eureka 中注册
    register-with-eureka: true
    # 在注册中心获取注册信息
    fetch-registry: true
    service-url:
      # 设置 eureka-server 的地址
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    # 设置微服务名称
    instance-id: gateway9527
    # 显示 ip
    prefer-ip-address: true