server:
  port: 9001

spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.23.21

management:
  endpoints:
    web:
      exposure:
        include: "*"